### ISSUE TITLE
Using a browser for this is way overkill and horribly slow

### ISSUE THREAD

**Issue by Kuuuube** [roogue/osu-collector-dl#1]
Not sure if you were aware but you can just pull full collections from the osu!collector api in a single request using the following: 
```
https://osucollector.com/api/collections/{id}
```
Not really making a feature request since I already have my own program to do this but just wanted to let you know.

**Comment by roogue** [comment]
Thanks for the notice, I am not aware that osu!Collector do actually provides an api for everything. However, I will not modify the source library as this is a great learning opportunity / future reference for myself. Also this program uses an alternative way to scrape all the datas, so might be useful in some cases(?)

Anyway, I know, it's hella slow.  :)

**Comment by roogue** [comment]
So, I am back and have time to review this. It is actually efficient to use the osu!Collector's api. I had updated an browser-less option for this program. Appreciate for the golden suggestion. 

- [Release v2.5.0](https://github.com/roogue/osu-collector-dl/releases/tag/v2.5.0)
