### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by tr3xz** [roogue/osu-collector-dl#13]
**Describe**
tried to download but had error bellow

**To Reproduce**
open with/without admin, 4991>1, had error
1. Download from the collection 4991
2. Wait until the error occurs ?

**Error log (If present):**
Failed when downloading [1895541] , due to error: TypeError: fetch failed
Failed when downloading [1899986] , due to error: TypeError: fetch failed
Downloading [1895541]
Retrying [1895541]
Failed when downloading [1889779] , due to error: TypeError: fetch failed
Downloading [1899986]
Retrying [1899986]
Failed when downloading [1872831] , due to error: TypeError: fetch failed
Downloading [1895541]
Retrying [1895541]
Downloading [1889779]
Retrying [1889779]
Downloading [1899986]
Retrying [1899986]
Downloading [1872831]
Download completed.
```
===Some Error===
```

**Expected behavior**
average? download?

**Screenshots**
![image](https://github.com/roogue/osu-collector-dl/assets/109140047/7fd3cd10-773c-438c-ad6a-ed60bb2ad262)

**Additional information:**
if im opening without admin perms, i have this error:

An error occurred: Error: 11:40:47 | [OcdlError]: FOLDER_GENERATION_FAILED - Error occurred while generating folder
Error: EPERM: operation not permitted, mkdir 'C:\apps\win-x64\Easy 200-300pp HDDT Maps [500+ Maps]'

- Operating System: [e.g. iOS]
windows 10
**Additional context**
i didnt touch config.

**Comment by roogue** [comment]
Thanks for bringing this to my attention. I will let you know if I release a patch. Sorry for the inconvenience :(

**Comment by roogue** [comment]
It's a bug that happened due to the changes/updates of the osu mirror API website. I am not sure what was the main cause of that, but switching to a different mirror api seems to solve the case. I had released a patch **[v2.7.3](https://github.com/roogue/osu-collector-dl/releases/tag/v2.7.3)**
