### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by JRoshyn** [roogue/osu-collector-dl#14]
**Describe**
![image-7](https://github.com/roogue/osu-collector-dl/assets/94510193/1d808ada-5465-4a72-91d8-4f612caaf7a8)

**To Reproduce**

1. Download from the collection 1346
2. Wait until the error occurs from start

**Error log (If present):**

```
===Some Error===
```

**Expected behavior**

**Screenshots**

**Additional information:**

- Operating System: [e.g. iOS]

**Additional context**

**Comment by roogue** [comment]
Hi Roshyn, I can download them without any problem, it might be because of a poor connection or region/firewall that blocked your connection to the osu mirror API service. Maybe you can try again with a VPN. I will further investigate this issue too, thanks for reporting.
