### ISSUE TITLE
Status code: 429 error 

### ISSUE THREAD

**Issue by Hindeko** [roogue/osu-collector-dl#20]
I've seen 2 issues about 418 error code, but what about 429 code, is it about blocked ip-adress too?
![image](https://github.com/roogue/osu-collector-dl/assets/121084270/e5af6bc7-4ce1-4630-ae82-84a6b4b768d4)

**Comment by roogue** [comment]
418 means blocked, and 429 means you're about to be blocked.

**Comment by Hindeko** [comment]
i got blocked :sob:

**Comment by roogue** [comment]
Don't use any of the download functionality at this moment, wait for the next update. The block would probably get removed after we(me and the service provider) come to a resolution or you can possibly bypass it by resetting your router.
