### ISSUE TITLE
[ Suggestion ] Download "ocdl-missing.log" missing files

### ISSUE THREAD

**Issue by 0daxelagnia** [roogue/osu-collector-dl#5]
- Make a new file to paste the file path or just a file to paste all the links. _# Something like "missing-beatmaps-list.txt"_
- Add an option in the terminal to check if the user wants to download the missing **Beatmaps**.
- Maybe making a folder exclusively to save the "ocdl-missing.log" with "**Collection Name** + **Date and time**" so it's easier to download and select the one you want to download.

Anyways, thanks for developing this amazing tool!

**Comment by roogue** [comment]
Thank you for your suggestion :) I will look into this later due to the fact that I am currently busy with my college thingy :p

**Comment by roogue** [comment]
I don't want to make the user experience further complex, since adding more options and files/folders would make some users confused, thus, I feel like attempt to download them with a different provider would be a better choice.

**Comment by roogue** [comment]
Close as implemented: [`v2.6.4`](https://github.com/roogue/osu-collector-dl/releases/tag/v2.6.4)
