### ISSUE TITLE
[Suggestion] Option to only generate .osdb

### ISSUE THREAD

**Issue by vpertys** [roogue/osu-collector-dl#7]
Since Collection Manager can be used to download missing beatmaps, it would be nice if there was an option to only generate the .osdb file and use Collection Manager to download the beatmaps so that the already existing maps don't have to be downloaded again.

**Comment by roogue** [comment]
Hello! Thanks for the suggestion.

You can actually close the terminal once the .osdb file was generated (Since it was generated first before the download starts). 

But yeah, it can be convenient for some people, if that option exists. I will consider it, thanks again.

**Comment by roogue** [comment]
Hello vpertys, thank you for your suggestion. After careful consideration, I have decided to reject it as I want to keep the focus of the project on providing an easy way to download every beatmap set from the website. Adding more options could make the project more complex and detract from its main purpose. However, I will be implementing a 3-second delay before the download begins to allow users to close the terminal once the .osdb file is generated.
